BOT_NAME = "scraper_service"
SPIDER_MODULES = ["scraper_service.spiders"]
NEWSPIDER_MODULE = "scraper_service.spiders"

# Polite scraping defaults
ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 1
DOWNLOAD_DELAY = 60.0

# AutoThrottle（負荷抑制）
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 60.0
AUTOTHROTTLE_MAX_DELAY = 300.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0

LOG_LEVEL = "INFO"
